# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: mylocal

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'




- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Build the Code'

- script: |
    npm run test:unit
  displayName: 'Run Unit Tests'

- script: |
    npm run test:integration
  displayName: 'Run Integration Tests'

- script: |
    npm run test:functional
  displayName: 'Run Functional Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results/*.xml'
  displayName: 'Publish Test Results'